{"name": "test_case_003", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <scripts.test_case.TestCase object at 0x03520FA0>\n\n    def test_case_003(self):\n>       assert 0\nE       assert 0\n\nscripts\\test_case.py:12: AssertionError"}, "start": 1614074861846, "stop": 1614074861846, "uuid": "6b49a7c9-adbe-4f06-9cde-ab042a0c7b68", "historyId": "e8fd5567553e5d13945a2323dd2dc166", "testCaseId": "eb0db0c1e7d73c1da60f66dc534fa2c0", "fullName": "scripts.test_case.TestCase#test_case_003", "labels": [{"name": "parentSuite", "value": "scripts"}, {"name": "suite", "value": "test_case"}, {"name": "subSuite", "value": "TestCase"}, {"name": "host", "value": "USER-20191018KD"}, {"name": "thread", "value": "10508-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "scripts.test_case"}]}